### PR TITLE
In-view Optimizations

### PR DESCRIPTION
**Pull request by lfre**
- Adds off method to registries ( https://github.com/camwiegert/in-view/pull/63 )
- Adds proxy to global check
- Removes global options, allows individual options per selector. If selector exists with different options, it generates a new one instead of overriding it.
- Adds support for Nodes and NodeList, modified from https://github.com/camwiegert/in-view/pull/41
- Moves offset, threshold and test functions to override options on a registry.
- Adds method to get a registry by selector name

### CODE REVIEW

**Comment by lneveu** [comment]
Awesome 👍 Did you plan to add support for the intersectionObserver API? 😄

**Comment by youradds** [comment]
Why hasn't this been merged yet? What a PITA! I'm trying to see if this is going to work with AJAX requests (doesn't seem to trigger on dynamic content), but the current build seems to be from 2 years ago :/

**Comment by lfre** [comment]
@youradds I agree. I recommend switching to https://github.com/aFarkas/lazysizes. It integrates the intersectionObserver API and MutationObserver too, so it just loads dynamic content. With `in-view`, you'd have to trigger a `check` right after.

**Comment by youradds** [comment]
@lfre thanks - will check that now :)

**Pull request closed without merging**
