### PR TITLE
added compatiblity for nodes and nodelists

### PR DESCRIPTION
**Pull request by nomiad**
this will add support for nodes and nodelists. I had to work around the registery thing, so if there is a better long term solution feel free to change it ;-)

### CODE REVIEW

**Comment by dan-gamble** [comment]
Just ran into this today, would like to see this merged :)

**Comment by ezekg** [comment]
Any update on this? What's blocking?

**Comment by camwiegert** [comment]
Definitely looking forward to this. Essentially, I'm pushing to get a release candidate for 1.0 out in the next few weeks which addresses this.

**Comment by camwiegert** [comment]
Also, if you're curious, there's a bit of discussion in #29 about where we're heading with this.

**Comment by nomiad** [comment]
i've read the other thread. Currently because i can't reference the registry with a selector i generate a unique id: Like Node-123. It does return a reference to that registry. The only thing what we would have to do is to store the key in the registry itself.

This way we could use
`
var reg = inView(document.querySelector("#myid"));
console.info(reg.id);
`

**Comment by pihvi** [comment]
Works great with this dependency in package jason:
"in-view": "nomiad/in-view#acceptdocumentnode"
Thanks!

I'd also like to see an option to pass an Array of nodes as I'm using jQuery and it returns an Array of nodes, not NodeList. Would make jQuery interop much simpler and simple to implement:
```
if (selector instanceof Array) {
          elements = selector;
          selector = "Node-"+nodecounter++;
}

```

**Comment by nomiad** [comment]
ok i've updated the branch to support now selectors as Array and also extended the registry to be able to store the selector.
var reg = inView(document.querySelector("#myid")); console.info(reg.selector);

**Comment by pihvi** [comment]
Wonderful! Works like a charm, thanks!

Just to show how nice this was: without Array support I had to wrap jQuery elements to a div and then find the elements from there to get the NodeList
```javascript
// elements contains ".element" elements as jQuery object
var node = $('<div>').append(elements)
var nodeListElements = node.get(0).querySelectorAll('.element')
inView(nodeListElements)...
```
and now it's just
```javascript
inView(elements.get())...
```

Hopefully this gets merged.

**Comment by denkristoffer** [comment]
Just as an FYI to anyone else having to support IE 11, the use of `Array.from()` in this PR requires either a polyfill or using a loop instead.

**Comment by pihvi** [comment]
Thanks for pointing that out! I actually disabled this for IE because of that, but in-view itself says it's for IE9+ so definitely this PR should not break that.

**Comment by nomiad** [comment]
Ups, didn't see that. Wanted to refactor it, but totally forgot it.
I'll change it to an oldschool solution.

**Comment by nomiad** [comment]
here you go

**Comment by pihvi** [comment]
Great! Tested on Mobile IE 11 and it works now.

**Comment by samburgers** [comment]
Any update on this yet?

**Comment by christippett** [comment]
Looking forward to this!

**Comment by KasperAndersson** [comment]
@camwiegert What's the status on this? Would really love to see this added to the lib.

**Pull request closed without merging**
